### ISSUE TITLE
Сергей, какие сейчас нужны работы\проекты?

### ISSUE THREAD

**Issue by LightVolk** [sbzenenko/DeveloperPath#4]
А то сейчас и не понять. Ты там работу делаешь, я вижу)

**Comment by sbzenenko** [comment]
Я заканчиваю основную часть API. Думаю, что сегодня закончу.
Есть задачи по расширению API. Посмотреть можно здесь https://dev.azure.com/sbenzenko/DeveloperPath/_workitems/edit/11/

**Comment by sbzenenko** [comment]
Добавил задачек в проект
https://dev.azure.com/sbenzenko/DeveloperPath/_workitems/
